// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinFormsApp3.Context.WinFormsApp3.Context;

#nullable disable

namespace WinFormsApp3.Migrations
{
    [DbContext(typeof(LOGIN_MANAGERContext))]
    partial class LOGIN_MANAGERContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WinFormsApp3.Models.FrontendUser", b =>
                {
                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pass_word")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_name");

                    b.ToTable("frontend", (string)null);
                });

            modelBuilder.Entity("WinFormsApp3.Models.KitchenUser", b =>
                {
                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pass_word")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_name");

                    b.ToTable("kitchen", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
